#!/usr/bin/env node
// Finds every build folder (<lab>/<model-slug>-<effort>/index.html), rewrites the
// "builds" list in models.json, and generates models.js, which the site loads.
// (A plain <script> works even when index.html is opened straight from disk.)
//
//   node scripts/sync-builds.mjs           validate folders, update models.json + models.js
//   node scripts/sync-builds.mjs --check   validate only (used on pull requests)
//
// Exits 1 if a folder can't be matched to a model and effort in models.json.
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const checkOnly = process.argv.includes('--check');
const manifestPath = join(root, 'models.json');
const sitePath = join(root, 'models.js');
const original = readFileSync(manifestPath, 'utf8');
const originalSite = existsSync(sitePath) ? readFileSync(sitePath, 'utf8') : '';
const data = JSON.parse(original);
const prompt = readFileSync(join(root, data.prompt), 'utf8').trim();
const efforts = Object.keys(data.efforts);
const labIds = new Set(data.labs.map(l => l.id));
const previous = new Map(data.builds.map(b => [b.id, b]));
const errors = [];
const warnings = [];
const builds = [];
const isDir = p => statSync(p).isDirectory();

for (const lab of data.labs) {
  const labDir = join(root, lab.id);
  if (!existsSync(labDir)) continue;
  for (const folder of readdirSync(labDir).sort()) {
    const dir = join(labDir, folder);
    if (folder.startsWith('.') || !isDir(dir)) continue;
    const id = `${lab.id}/${folder}`;
    if (!existsSync(join(dir, 'index.html'))) { errors.push(`${id}: missing index.html`); continue; }

    const effort = efforts.find(e => folder.endsWith(`-${e}`));
    if (!effort) { errors.push(`${id}: folder name must end in -<effort>, one of: ${efforts.join(', ')}`); continue; }
    const slug = folder.slice(0, -(effort.length + 1));
    const model = lab.models.find(m => m.slug === slug || m.aliases?.includes(slug));
    if (!model) {
      errors.push(`${id}: "${slug}" is not a ${lab.name} model. Known: ${lab.models.map(m => m.slug).join(', ')} (or add it to models.json)`);
      continue;
    }
    const twin = builds.find(b => b.model === model.slug && b.lab === lab.id && b.effort === effort);
    if (twin) { errors.push(`${id}: duplicates ${twin.id} (same model and effort)`); continue; }
    if (Array.isArray(model.efforts) && !model.efforts.includes(effort)) {
      warnings.push(`${id}: ${model.name} isn't listed with "${effort}" effort in models.json`);
    }

    const promptPath = join(dir, 'prompt.txt');
    if (!existsSync(promptPath)) warnings.push(`${id}: no prompt.txt, assuming the root prompt.txt was used`);
    else if (readFileSync(promptPath, 'utf8').trim() !== prompt) errors.push(`${id}: prompt.txt differs from the root prompt.txt`);

    // Keep any hand-added fields (e.g. "by") from the previous entry.
    builds.push({ ...previous.get(id), id, lab: lab.id, model: model.slug, effort });
  }
}

// Build folders under a top-level directory that isn't a lab yet.
for (const top of readdirSync(root)) {
  const dir = join(root, top);
  if (top.startsWith('.') || labIds.has(top) || ['scripts', 'node_modules'].includes(top) || !isDir(dir)) continue;
  if (readdirSync(dir).some(f => existsSync(join(dir, f, 'index.html')))) {
    errors.push(`${top}/: unknown lab. Add { "id": "${top}", ... } to "labs" in models.json`);
  }
}

for (const w of warnings) console.warn(`warning: ${w}`);
if (errors.length) {
  for (const e of errors) console.error(`error: ${e}`);
  process.exit(1);
}

const next = format({ ...data, builds });
const nextSite = siteData({ ...data, builds });
const changed = next !== original || nextSite !== originalSite;
if (checkOnly) {
  console.log(`ok: ${builds.length} builds${changed ? ' (models.json and models.js get updated after merge)' : ''}`);
} else if (changed) {
  writeFileSync(manifestPath, next);
  writeFileSync(sitePath, nextSite);
  console.log(`updated models.json and models.js: ${builds.length} builds`);
} else {
  console.log(`models.json and models.js are up to date: ${builds.length} builds`);
}

// models.js = models.json + the prompt text + per-build file stats, so the page needs no fetches.
function siteData(d) {
  const withStats = d.builds.map(b => {
    const html = readFileSync(join(root, b.id, 'index.html'), 'utf8');
    const three = html.match(/three@0\.(\d+)\.\d+|three\.js\/r(\d+)/);
    return {
      ...b,
      bytes: Buffer.byteLength(html),
      lines: html.split('\n').length - (html.endsWith('\n') ? 1 : 0),
      three: three ? `r${three[1] || three[2]}` : null,
    };
  });
  return '// Generated by scripts/sync-builds.mjs from models.json. Edit models.json, not this file.\n'
    + `window.MODELS_DATA = ${JSON.stringify({ ...d, builds: withStats, promptText: prompt }, null, 2)};\n`;
}

// One model / build per line keeps diffs readable.
function format(d) {
  const inline = v => Array.isArray(v) ? `[${v.map(inline).join(', ')}]`
    : v && typeof v === 'object' ? `{ ${Object.entries(v).map(([k, x]) => `${JSON.stringify(k)}: ${inline(x)}`).join(', ')} }`
    : JSON.stringify(v);
  const list = (items, indent) => items.length
    ? `[\n${items.map(x => indent + inline(x)).join(',\n')}\n${indent.slice(2)}]`
    : '[]';
  const fields = Object.entries(d).map(([key, value]) => {
    if (key !== 'labs') return `${JSON.stringify(key)}: ${Array.isArray(value) ? list(value, '    ') : inline(value)}`;
    const labs = value.map(({ models, ...lab }) => {
      const head = Object.entries(lab).map(([k, v]) => `${JSON.stringify(k)}: ${inline(v)}`).join(', ');
      return `    {\n      ${head},\n      "models": ${list(models, '        ')}\n    }`;
    });
    return `"labs": [\n${labs.join(',\n')}\n  ]`;
  });
  return `{\n  ${fields.join(',\n  ')}\n}\n`;
}
